"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'ppid_dokumen',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'mozilla_django_oidc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.OIDCSessionMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.oidc_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.mysql'),
        'NAME': config('DB_NAME', default='ppid_dokumen'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# =============================================================================
# Keycloak OIDC Configuration (mozilla-django-oidc)
# =============================================================================

OIDC_ENABLED = config('OIDC_ENABLED', default=False, cast=bool)

# Keycloak server URLs (harus selalu didefinisikan karena mozilla-django-oidc
# membaca settings saat import, meski OIDC belum aktif)
OIDC_KEYCLOAK_URL = config('OIDC_KEYCLOAK_URL', default='https://sso.example.com').rstrip('/')
OIDC_KEYCLOAK_REALM = config('OIDC_KEYCLOAK_REALM', default='master')
_OIDC_BASE = f"{OIDC_KEYCLOAK_URL}/realms/{OIDC_KEYCLOAK_REALM}/protocol/openid-connect"

OIDC_OP_AUTHORIZATION_ENDPOINT = f"{_OIDC_BASE}/auth"
OIDC_OP_TOKEN_ENDPOINT = f"{_OIDC_BASE}/token"
OIDC_OP_USER_ENDPOINT = f"{_OIDC_BASE}/userinfo"
OIDC_OP_JWKS_ENDPOINT = f"{OIDC_KEYCLOAK_URL}/realms/{OIDC_KEYCLOAK_REALM}/protocol/openid-connect/certs"
OIDC_OP_LOGOUT_ENDPOINT = f"{_OIDC_BASE}/logout"

# Client credentials (dari Keycloak client)
OIDC_RP_CLIENT_ID = config('OIDC_RP_CLIENT_ID', default='ppid-django')
OIDC_RP_CLIENT_SECRET = config('OIDC_RP_CLIENT_SECRET', default='')

# Algorithm & scopes
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid email profile"

# Redirect setelah login/logout
LOGIN_REDIRECT_URL = "/admin/"
LOGOUT_REDIRECT_URL = "/admin/"

# Otomatis buat user Django saat pertama login via Keycloak
OIDC_CREATE_USER = True

# Session refresh (cek token masih valid)
OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = 300  # 5 menit

# Role mapping: nama role/group Keycloak yang akan dijadikan staff/superuser
OIDC_STAFF_ROLES = config('OIDC_STAFF_ROLES', default='ppid-staff', cast=Csv())
OIDC_SUPERUSER_ROLES = config('OIDC_SUPERUSER_ROLES', default='ppid-admin', cast=Csv())

if OIDC_ENABLED:
    AUTHENTICATION_BACKENDS = [
        'core.oidc.KeycloakOIDCAuthenticationBackend',
        'django.contrib.auth.backends.ModelBackend',
    ]

    # Override admin logout agar logout dari Keycloak juga
    LOGOUT_REDIRECT_URL = "/oidc/logout/"