# Generated by Django 5.2.15 on 2026-07-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriInformasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori Informasi',
                'verbose_name_plural': 'Kategori Informasi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Unit Kerja',
                'verbose_name_plural': 'Unit Kerja',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='DokumenPPID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(blank=True, max_length=100, verbose_name='Nomor')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('tentang', models.CharField(max_length=255, verbose_name='Tentang')),
                ('detail', models.TextField(blank=True, verbose_name='Detail')),
                ('klasifikasi', models.CharField(choices=[('umum', 'Umum'), ('terbatas', 'Terbatas'), ('dikecualikan', 'Dikecualikan')], default='umum', max_length=20)),
                ('status', models.CharField(choices=[('berlaku', 'Berlaku'), ('kadaluarsa', 'Kadaluarsa'), ('proses', 'Dalam Proses')], default='berlaku', max_length=20)),
                ('file', models.FileField(upload_to='dokumen_ppid/%Y/', verbose_name='File')),
                ('penulis', models.CharField(max_length=100, verbose_name='Penulis/Pengunggah')),
                ('tanggal_terbit', models.DateTimeField(verbose_name='Tanggal Terbit')),
                ('diunduh', models.PositiveIntegerField(default=0, verbose_name='Jumlah Diunduh')),
                ('kategori_informasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dokumen', to='ppid_dokumen.kategoriinformasi')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dokumen', to='ppid_dokumen.unitkerja')),
            ],
            options={
                'verbose_name': 'Dokumen PPID',
                'verbose_name_plural': 'Dokumen PPID',
                'ordering': ['-tanggal_terbit'],
            },
        ),
    ]
