# Generated by Django 5.2.15 on 2026-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid_dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenppid',
            name='file_url',
            field=models.URLField(blank=True, help_text='Isi URL jika file sudah tersimpan di penyimpanan lain (Google Drive, cloud storage, dsb.)', max_length=500, verbose_name='URL File Eksternal'),
        ),
        migrations.AlterField(
            model_name='dokumenppid',
            name='file',
            field=models.FileField(blank=True, upload_to='dokumen_ppid/%Y/', verbose_name='File Upload'),
        ),
    ]
