# Generated by Django 5.2.15 on 2026-07-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid_dokumen', '0002_dokumenppid_file_url_alter_dokumenppid_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama folder di CDN, contoh: AAKK, AUPK, LP2M, PPID, SPI', max_length=100, unique=True, verbose_name='Nama Organisasi')),
                ('deskripsi', models.CharField(blank=True, help_text='Nama lengkap, contoh: Akademik dan Kemahasiswaan', max_length=255, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Organisasi',
                'verbose_name_plural': 'Organisasi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='UnitOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama folder unit di CDN, contoh: Administrasi Akademik', max_length=100, verbose_name='Nama Unit')),
                ('deskripsi', models.CharField(blank=True, max_length=255, verbose_name='Deskripsi')),
                ('organisasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='ppid_dokumen.organisasi')),
            ],
            options={
                'verbose_name': 'Unit Organisasi',
                'verbose_name_plural': 'Unit Organisasi',
                'ordering': ['organisasi__nama', 'nama'],
                'unique_together': {('organisasi', 'nama')},
            },
        ),
    ]
