# Generated by Django 5.1.1 on 2026-07-07 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid_dokumen', '0003_organisasi_unitorganisasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDNActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('rename', 'Rename'), ('delete', 'Hapus')], max_length=10, verbose_name='Aksi')),
                ('file_path', models.CharField(max_length=500, verbose_name='Path File')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nama File')),
                ('detail', models.TextField(blank=True, help_text='Info tambahan, misal: nama baru saat rename, jumlah file saat upload', verbose_name='Detail')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdn_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Log Aktivitas CDN',
                'verbose_name_plural': 'Log Aktivitas CDN',
                'ordering': ['-timestamp'],
            },
        ),
    ]
