# Generated by Django 5.2.15 on 2026-07-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid_dokumen', '0004_cdnactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(help_text='Tahun folder di CDN, contoh: 2025, 2026', unique=True, verbose_name='Tahun')),
            ],
            options={
                'verbose_name': 'Tahun Dokumen',
                'verbose_name_plural': 'Tahun Dokumen',
                'ordering': ['-tahun'],
            },
        ),
    ]
