# Generated by Django 5.1.1 on 2026-07-08 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid_dokumen', '0005_tahundokumen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Jenis')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil di dropdown dan halaman publik (kecil = di atas)', verbose_name='Urutan Tampil')),
            ],
            options={
                'verbose_name': 'Jenis Dokumen',
                'verbose_name_plural': 'Jenis Dokumen',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='CDNFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path relatif dari root CDN, misal: 2025/AUPK/dokumen.pdf', max_length=500, unique=True, verbose_name='Path di CDN')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nama File')),
                ('tahun', models.CharField(blank=True, max_length=4, verbose_name='Tahun')),
                ('deskripsi', models.CharField(blank=True, help_text='Keterangan singkat tentang isi dokumen', max_length=500, verbose_name='Deskripsi/Keterangan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Upload')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Ukuran (bytes)')),
                ('organisasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdn_files', to='ppid_dokumen.organisasi', verbose_name='Organisasi')),
                ('unit_organisasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdn_files', to='ppid_dokumen.unitorganisasi', verbose_name='Unit Organisasi')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdn_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Diupload oleh')),
                ('jenis_dokumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdn_files', to='ppid_dokumen.jenisdokumen', verbose_name='Jenis Dokumen')),
            ],
            options={
                'verbose_name': 'File CDN',
                'verbose_name_plural': 'File CDN',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
