# Generated by Django 5.1.1 on 2026-07-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppid_dokumen', '0006_jenisdokumen_cdnfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdnfile',
            name='file_path',
            field=models.CharField(help_text='Path relatif dari root CDN, misal: 2025/AUPK/dokumen.pdf', max_length=255, unique=True, verbose_name='Path di CDN'),
        ),
    ]
